# Generated by Django 5.0.6 on 2024-06-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
